namespace Chronicle.RuleSets.Werewolf.CharacterCreation;

public static class WerewolfCombatManeuverCatalog
{
    public static IReadOnlyList<WerewolfCombatManeuver> Entries { get; } =
    [
        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Bite,
            "Lines 3129-3132",
            WerewolfAbilityIdentifiers.Brawl,
            5,
            null,
            [WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "Strength + 1",
            WerewolfDamageCategory.Aggravated.ToString(),
            1,
            false,
            false,
            null,
            "Crinos and Lupus only"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.BiteGlabro,
            "Lines 3130",
            WerewolfAbilityIdentifiers.Brawl,
            8,
            null,
            [WerewolfFormIdentifiers.Glabro],
            false,
            null,
            "Strength - 1",
            WerewolfDamageCategory.Aggravated.ToString(),
            1,
            false,
            false,
            null,
            "Glabro optional bite with penalty"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Tackle,
            "Lines 3132-3135",
            WerewolfAbilityIdentifiers.Brawl,
            7,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "Strength",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Requires resisted Athletics test to avoid falling; Lethal against unprotected humans in Crinos/Hispo"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Claw,
            "Lines 3136-3139",
            WerewolfAbilityIdentifiers.Brawl,
            6,
            null,
            [WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo],
            false,
            null,
            "Strength + 1",
            WerewolfDamageCategory.Aggravated.ToString(),
            1,
            false,
            false,
            null,
            "Crinos and Hispo only"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Disarm,
            "Lines 3140-3143",
            WerewolfAbilityIdentifiers.Melee,
            0,
            1,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            true,
            WerewolfAbilityIdentifiers.Melee,
            "Special",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Opponent Strength tested against successes to disarm; Brawl without weapon difficulty 8"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Grapple,
            "Lines 3144-3147",
            WerewolfAbilityIdentifiers.Brawl,
            6,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            false,
            null,
            "Strength",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Key or immobilization"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Kick,
            "Lines 3148-3151",
            WerewolfAbilityIdentifiers.Brawl,
            7,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            false,
            null,
            "Strength + 1",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Lethal in Crinos against humans"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Punch,
            "Lines 3152-3155",
            WerewolfAbilityIdentifiers.Brawl,
            6,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            false,
            null,
            "Strength",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Lethal in Crinos against humans"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Sweep,
            "Lines 3156-3159",
            WerewolfAbilityIdentifiers.Brawl,
            8,
            1,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "None",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Hispo/Lupus +1 difficulty; Crinos can use arms; leaves opponent prone"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.MeleeWeapon,
            "Lines 3160-3163",
            WerewolfAbilityIdentifiers.Melee,
            0,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            true,
            WerewolfAbilityIdentifiers.Melee,
            "Variable",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            false,
            false,
            null,
            "Forms with manipulation capability; damage varies by weapon; silver causes aggravated"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.EvasiveAction,
            "Lines 3166-3168",
            WerewolfAbilityIdentifiers.Dodge,
            6,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "None",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            true,
            false,
            null,
            "Each success subtracts 1 success from opponent attack; more successes than attacker = -1 difficulty on own attack next turn; requires prior declaration"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Incapacitate,
            "Lines 3169-3171",
            WerewolfAbilityIdentifiers.Brawl,
            8,
            null,
            [WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "Strength + Cripple",
            WerewolfDamageCategory.Aggravated.ToString(),
            1,
            false,
            false,
            null,
            "Directed at legs; halves quadruped movement; cripples bipeds"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.IronMandible,
            "Lines 3172-3174",
            WerewolfAbilityIdentifiers.Brawl,
            6,
            1,
            [WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "None",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            true,
            true,
            WerewolfCombatIdentifiers.Bite,
            "Requires prior bite success; resisted Strength + Athletics to maintain; escape attempts resisted Strength + Brawl"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.SavageLeap,
            "Lines 3175-3177",
            WerewolfAbilityIdentifiers.Athletics,
            8,
            null,
            [WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos],
            false,
            null,
            "Strength + 1",
            WerewolfDamageCategory.Aggravated.ToString(),
            2,
            true,
            true,
            WerewolfCombatIdentifiers.Tackle,
            "Requires prior Athletics success (jump table); strike and land out of range; Homid with Rabbit Leap Gift only"),

        new WerewolfCombatManeuver(
            WerewolfCombatIdentifiers.Taunt,
            "Lines 3178-3180",
            WerewolfAbilityIdentifiers.Expression,
            0,
            null,
            [WerewolfFormIdentifiers.Homid, WerewolfFormIdentifiers.Glabro, WerewolfFormIdentifiers.Crinos, WerewolfFormIdentifiers.Hispo, WerewolfFormIdentifiers.Lupus],
            false,
            null,
            "None",
            WerewolfDamageCategory.Bashing.ToString(),
            1,
            true,
            false,
            null,
            "Every 2 successes = opponent loses 1 die in next action; pack effects cumulative; vs Garou: Manipulation + Expression; vs non-Garou: Intimidation; difficulty: Wits + 4 of opponent")
    ];
}
