using System.Collections.ObjectModel;

namespace Chronicle.RuleSets.Werewolf.CharacterCreation;

public static class WerewolfGiftCatalog
{
    private static readonly WerewolfGiftDefinition[] All = new[]
    {
        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidMasterOfFire,
            "Master of Fire",
            "Mestre do Fogo",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Repairs fire damage as bashing for the scene.",
            "Repara dano por fogo como contusão durante a cena.",
            "Line 1733"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisCreateElement,
            "Create Element",
            "Criar Elemento",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Gnosis",
            null,
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Creates a small amount of natural element (earth, water, fire, air). Each success creates about 30 cubic centimeters (up to 50 kg) within 20 meters. Created flames cause 1 health level per success (max 3).",
            "Cria pequena quantidade de elemento natural (terra, água, fogo, ar). Cada sucesso cria cerca de 30 cm³ (até 50 kg) num raio de 20 metros. Chamas causam 1 nível de dano por sucesso (máx 3).",
            "Line 1788"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.LupusHareLeap,
            "Hare Leap",
            "Salto da Lebre",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Lupus,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Athletics",
            7,
            WerewolfGiftDurationType.Instant,
            0,
            "Doubles the Garou's normal jump distance on a successful test.",
            "Dobra a distância normal de salto do Garou em caso de sucesso.",
            "Line 1827"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RagabashOpenSeal,
            "Open Seal",
            "Abrir Objetos",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ragabash,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Opens almost any physical locked device. Difficulty equals local Película level.",
            "Abre quase qualquer dispositivo físico trancado. Dificuldade igual ao nível local da Película.",
            "Line 1874"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.TheurgeSpiritSpeech,
            "Spirit Speech",
            "Comunicação com Espíritos",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Theurge,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Intuitively understands the language of spirits encountered casually, even if they do not wish to dialogue.",
            "Compreende intuitivamente a linguagem de espíritos encontrados casualmente, mesmo que não desejem dialogar.",
            "Line 1925"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.PhilodoxResistPain,
            "Resist Pain",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Philodox,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Ignores all wound penalties for the rest of the scene through force of will.",
            "Ignora completamente todas as penalidades de ferimentos durante o resto da cena.",
            "Line 1973"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GalliardBeastSpeech,
            "Beast Speech",
            "Chamado da Wyrm / Chamado da Wyld",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Galliard,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Empathy",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Emits a vigorous howl that mobilizes packs at great distances and exhorts the sept. The Narrator defines applicable bonuses.",
            "Emite um uivo vigoroso que mobiliza matilhas a grandes distâncias e exorta a seita. O Narrador define os bônus aplicáveis.",
            "Line 2019"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounFallingTouch,
            "Falling Touch",
            "Toque da Queda",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Medicine",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Knocks the opponent prone with a simple touch. Test Dexterity + Medicine vs target Vigor + Athletics. Each success knocks the victim down.",
            "Derruba o adversário ao solo com um simples toque. Teste de Destreza + Medicina contra Vigor + Esportes do alvo. Cada sucesso derruba a vítima.",
            "Line 2070"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersControlSimpleMachine,
            "Control Simple Machine",
            "Controle de Máquinas Simples",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Willpower,
            1,
            "Manipulation",
            "Crafts",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Commands spirits of simple machines (levers, doors, pulleys).",
            "Comanda espíritos de máquinas simples (alavancas, portas, roldanas).",
            "Line 2107"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersDiagnostics,
            "Diagnostics",
            "Diagnosticar",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Perception",
            "Crafts",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Instantly identifies mechanical defects and convinces the machine spirit to assist in repair. Reduces repair time by half and subtracts successes from total repair difficulty.",
            "Identifica defeitos mecânicos instantaneamente e convence o espírito da máquina a auxiliar no conserto. Reduz o tempo de reparo pela metade.",
            "Line 2110"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersTrickShot,
            "Trick Shot",
            "Número de Tiro",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Adds permanent Glory rating to indirect shooting maneuvers. Does not cause direct damage.",
            "Adiciona o nível de Glória permanente à parada de dados em manobras de tiro indiretas. Não causa dano direto.",
            "Line 2113"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisRazorClaws,
            "Razor Claws",
            "Garras Afiadas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Rage,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Sharpens claws like razors against a hard surface. Grants +1 damage die with claw attacks for the scene. Requires 1 turn of preparation.",
            "Afi as garras como navalhas ao raspá-las contra uma superfície dura. Concede +1 dado de dano em ataques com garras durante a cena. Requer 1 turno de preparação.",
            "Line 2147"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisResistPain,
            "Resist Pain",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Ignores all wound penalties for the rest of the scene through force of will.",
            "Ignora completamente todas as penalidades de ferimentos durante o resto da cena.",
            "Line 2150"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisVisageOfFenris,
            "Visage of Fenris",
            "Semblante de Fenris",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Assumes a larger, fearsome physical presence that inspires allies and terrifies rivals. Grants +1 to Social tests for allies and -1 to initiative for adversaries. Duration: one scene.",
            "Assume um porte físico maior, temível e imponente que inspira aliados e aterroriza rivais. Concede +1 em testes Sociais para aliados e -1 na iniciativa de adversários. Dura uma cena.",
            "Line 2153"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaFaerieLight,
            "Faerie Light",
            "Luz das Fadas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Wits",
            "Enigmas",
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Conjures a small bouncing sphere of light to illuminate the environment or distract enemies. Lasts 1 turn per success, or the entire scene with 1 Gnosis point.",
            "Conjura uma pequena esfera de luz saltitante para iluminar o ambiente ou distrair inimigos. Dura 1 turno por sucesso, ou a cena toda com 1 ponto de Gnose.",
            "Line 2188"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaPersuasion,
            "Persuasion",
            "Persuasão",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Makes the Fianna more persuasive and credible when interacting with others. On success, the Narrator reduces all Social test difficulties by 1 for the rest of the scene.",
            "Torna o Fianna mais persuasivo e credível ao interagir com outras pessoas. Em caso de sucesso, o Narrador reduz em 1 ponto as dificuldades de todos os testes Sociais durante o resto da cena.",
            "Line 2191"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaResistToxin,
            "Resist Toxin",
            "Resistência a Toxinas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Survival",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Adapts the organism to nullify common poisons after festive rituals. Cancels common poisons and grants +3 dice to Stamina against Wyrm toxins for the scene.",
            "Adapta o organismo para anular venenos convencionais após rituais festivos. Anula venenos comuns e concede +3 dados ao Vigor contra toxinas da Wyrm durante uma cena.",
            "Line 2193"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaMercy,
            "Mercy",
            "Misericórdia",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "All natural body damage (claws and fangs, without weapons) becomes bashing for the scene.",
            "Todo o dano infligido pelo próprio corpo (garras e dentes, sem armas) torna-se contundente durante a cena.",
            "Line 2226"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaMothersTouch,
            "Mother's Touch",
            "Toque da Mãe",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Intelligence",
            "Medicine",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Heals wounds (including aggravated) of any living creature by touch. Each success repairs 1 health level. Difficulty equals target's Fury or 6 for non-Garou. Can heal Battle Scars with a second Gnosis point in the same scene.",
            "Cicatriza ferimentos (inclusive agravados) de qualquer criatura viva por imposição de mãos. Cada sucesso repara 1 nível de vitalidade. Dificuldade igual à Fúria do alvo ou 6 para não-Garou.",
            "Line 2231"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesBreathOfTheWyrm,
            "Breath of the Wyrm",
            "Hálito da Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Requires touch to open sky in natural environment. Grants +1 die to Mental tests and +1 difficulty to target's Fury tests for the next scene. Difficulty 6 for humans, 5 for Garou.",
            "Requer toque a céu aberto em ambiente natural. Concede +1 dado em testes Mentais e +1 na dificuldade de testes de Fúria do alvo na cena seguinte.",
            "Line 2263"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesHeightenedSenses,
            "Heightened Senses",
            "Sentidos Aguçados",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Elevates senses to lupine levels. Homid/Glabro: reduces Perception difficulties by 2. Crinos/Hispo/Lupus: reduces Perception difficulties by 3 and grants +1 die to Primal Instinct.",
            "Eleva os sentidos a patamares lupinos. Hominídea/Glabro: reduz em 2 as dificuldades de Percepção. Crinos/Hispo/Lupina: reduz em 3 as dificuldades de Percepção e concede +1 dado em Instinto Primitivo.",
            "Line 2266"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesSenseWyrm,
            "Sense Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Mystic sense to detect Wyrm manifestations, objects, or people tainted by the Wyrm. Difficulty 6 for a nearby fomor, 8 for a Cursed one's trail.",
            "Sentido místico para perceber manifestações, objetos ou pessoas maculadas pela Wyrm. Dificuldade 6 para um fomor próximo, 8 para o rastro de um Maldito.",
            "Line 2268"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsBeastSpeech,
            "Beast Speech",
            "Comunicação com Animais",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "AnimalEmpathy",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Communicates with any animal species. One test per species/encounter.",
            "Comunica-se com qualquer espécie animal. Um teste por espécie/encontro.",
            "Line 2299"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsWolfAtTheDoor,
            "Wolf at the Door",
            "O Lobo Bate à Porta",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "PrimalInstinct",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Infuses humans with primal fear and deep aversion to the forest. Direct eye contact required. Target hesitates to leave home and loses 2 dice on all Mental and Social tests for the scene.",
            "Infunde em seres humanos um medo primal e aversão profunda à floresta. Contato visual direto. O alvo hesita em sair de casa e perde 2 dados em paradas Mentais e Sociais durante a cena.",
            "Line 2301"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsScentOfRunningWater,
            "Scent of Running Water",
            "Simular o Cheiro de Água Corrente",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Completely disguises the Garou's scent, making it impossible to track by smell. Increases difficulty of any tracking test by 2.",
            "Disfarça completamente o cheiro do Garou, tornando-o impossível de rastrear por faro. Aumenta em 2 pontos a dificuldade de qualquer teste para rastrear o personagem.",
            "Line 2304"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersSilence,
            "Silence",
            "Silêncio",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Muffles any sound produced by the Garou to facilitate stealthy approaches. Each success adds +1 to the difficulty of others hearing the Garou during the scene.",
            "Abafa qualquer som produzido pelo Garou para facilitar aproximações furtivas. Cada sucesso adiciona +1 ponto à dificuldade de outras pessoas ouvirem o Garou durante uma cena.",
            "Line 2339"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersSpeedOfThought,
            "Speed of Thought",
            "Velocidade do Pensamento",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Instantly doubles the Garou's running speed for the scene.",
            "Duplica instantaneamente a velocidade de corrida do lobisomem durante a cena.",
            "Line 2342"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsLambentFlame,
            "Lambent Flame",
            "Chama Tremulante",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Envelopes the body in bright silver light that protects against direct attacks and illuminates the environment (15-meter radius). Unarmed attacks against the Garou receive +1 difficulty, while ranged attacks receive -1 bonus.",
            "Envolve o corpo em uma luz prateada brilhante que protege contra ataques diretos e ilumina o ambiente (raio de 15 metros). Ataques desarmados recebem +1 de dificuldade, enquanto ataques à distância recebem -1 de bônus.",
            "Line 2374"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsFalconsGrasp,
            "Falcon's Grasp",
            "Nas Garras do Falcão",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Rage,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Allows closing hands or jaws hermetically, making it nearly impossible to escape the grip. Strength is considered +3 for grapples and jaw maneuvers without adding damage. Can activate both hands/jaws for 2 Rage.",
            "Permite fechar as mãos ou mandíbulas de forma hermética, tornando quase impossível escapar do aperto. A Força é considerada 3 pontos superior em agarramentos e manobras de mandíbula de ferro.",
            "Line 2377"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersCooking,
            "Cooking",
            "Culinária",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Wits",
            "Survival",
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Converts trash, scrap metal, or debris into an edible, satisfying mash. Difficulty 6 for harmless materials, 10 for toxic substances.",
            "Converte lixo, jatos de metal ou detritos em um mingau comestível e saciador. Dificuldade 6 para materiais inócuos, 10 para substâncias tóxicas.",
            "Line 2411"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersStickyFingers,
            "Sticky Fingers",
            "Grude",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            null,
            WerewolfGiftDurationType.Scene,
            1,
            "Allows joking with a pack or caern totem to obtain temporary treatment as a member. Requires prostration. Grants benefits for one day.",
            "Permite gracejar-se com o totem de uma matilha ou de um caern para obter tratamento temporário como membro. Requer prostração. Concede os benefícios por um dia.",
            "Line 2414"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsSeizingTheEdge,
            "Seizing the Edge",
            "Aproveitar a Vantagem",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Inclines resisted tests and ties in favor of the Shadow Lord. Lasts one entire scene.",
            "Inclina testes resistidos e empates a favor do Senhor das Sombras. Dura uma cena inteira.",
            "Line 2448"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsAuraOfConfidence,
            "Aura of Confidence",
            "Aura de Confiança",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Projects a superior and controlled aura that blocks aura analysis and flaw detection. Active for one scene on success.",
            "Projeta uma aura superior e controlada que bloqueia análises de aura e detecção de falhas. Ativa por uma cena em caso de sucesso.",
            "Line 2451"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsFatalFlaw,
            "Fatal Flaw",
            "Fraquezas Fatais",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Empathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Identifies critical vulnerabilities of a target to maximize damage in combat. Requires 1 turn of concentration. Each success grants +1 damage die for the scene. Difficulty equals target's Wits + Subterfuge.",
            "Identifica vulnerabilidades críticas de um alvo para maximizar o dano em combate. Requer 1 turno de concentração. Cada sucesso concede +1 dado de dano para a cena.",
            "Line 2454"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaSpiritSpeech,
            "Spirit Speech",
            "Comunicação com Espíritos",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Intuitively understands the language of spirits encountered casually, even if they do not wish to dialogue. Identical to Theurge Spirit Speech.",
            "Compreende intuitivamente a linguagem de espíritos encontrados casualmente, mesmo que não desejem dialogar. Idêntico ao Dom dos Theurges.",
            "Line 1925"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaShroud,
            "Shroud",
            "Mortalha",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Conceals the Uktena from supernatural detection. Spirits and magical senses find it harder to perceive the Uktena.",
            "Concele o Uktena de detecção sobrenatural. Espíritos e sentidos mágicos têm mais dificuldade em perceber o Uktena.",
            "Line 831"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaSenseMagic,
            "Sense Magic",
            "Sentir Magia",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Detects magical auras, fetishes, and active enchantments in the vicinity.",
            "Detecta auras mágicas, fetiches e encantamentos ativos nas proximidades.",
            "Line 831"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoCamouflage,
            "Camouflage",
            "Camuflagem",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Blends into snowy or natural terrain. Each success adds +1 difficulty to Perception tests to spot the Wendigo. In snow, this can be nearly automatic.",
            "Mistura-se com terreno nevado ou natural. Cada sucesso adiciona +1 de dificuldade a testes de Percepção para detectar o Wendigo.",
            "Line 848"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoCallTheBreeze,
            "Call the Breeze",
            "Invocar a Brisa",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Summons a chill wind or breeze. Can be used to cool the environment, carry scents, or obscure vision slightly.",
            "Invoca um vento frio ou brisa. Pode ser usado para resfriar o ambiente, carregar odores ou obscurecer a visão levemente.",
            "Line 848"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidSimularOdorDeHomem,
            "Simular Odor de Homem",
            "Simular Odor de Homem",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Acentua o cheiro de ser humano ao redor do Garou, deixando animais selvagens apreensivos e fazendo com que animais domésticos o reconheçam como mes...",
            "Acentua o cheiro de ser humano ao redor do Garou, deixando animais selvagens apreensivos e fazendo com que animais domésticos o reconheçam como mes...",
            "Line 1739"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidPerturbarTecnologia,
            "Perturbar Tecnologia",
            "Perturbar Tecnologia",
            2,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Manipulation",
            "Crafts",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Causa falhas temporárias em dispositivos tecnológicos num raio de 15 metros. Custa 1 ponto de Gnose e exige um teste de Manipulação + Ofícios. Cada...",
            "Causa falhas temporárias em dispositivos tecnológicos num raio de 15 metros. Custa 1 ponto de Gnose e exige um teste de Manipulação + Ofícios. Cada...",
            "Line 1746"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisRaivaPrimordial,
            "Raiva Primordial",
            "Raiva Primordial",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Canaliza a raiva acumulada no coração para inflamar a Fúria, sacrificando o próprio corpo. O impuro pode sacrificar um único nível de vitalidade (t...",
            "Canaliza a raiva acumulada no coração para inflamar a Fúria, sacrificando o próprio corpo. O impuro pode sacrificar um único nível de vitalidade (t...",
            "Line 1791"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisSentirAWyrm,
            "Sentir a Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Concede um sentido místico para perceber manifestações, objetos ou pessoas maculadas pela Wyrm. Teste de Percepção + Ocultismo (dificuldade 6 para ...",
            "Concede um sentido místico para perceber manifestações, objetos ou pessoas maculadas pela Wyrm. Teste de Percepção + Ocultismo (dificuldade 6 para ...",
            "Line 1794"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisCavar,
            "Cavar",
            "Cavar",
            2,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Strength",
            "Athletics",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Concede a habilidade de abrir túneis rapidamente na terra usando garras (exige forma Crinos, Hispo ou Lupina). Teste de Força + Esportes (dificulda...",
            "Concede a habilidade de abrir túneis rapidamente na terra usando garras (exige forma Crinos, Hispo ou Lupina). Teste de Força + Esportes (dificulda...",
            "Line 1798"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisOlhosDeGato,
            "Olhos de Gato",
            "Olhos de Gato",
            3,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Concede visão perfeita na mais completa escuridão (os olhos brilham com luz verde). Ativação livre (sem custos ou testes). Anula penalidades de dad...",
            "Concede visão perfeita na mais completa escuridão (os olhos brilham com luz verde). Ativação livre (sem custos ou testes). Anula penalidades de dad...",
            "Line 1808"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.LupusSentidosAgucados,
            "Sentidos Aguçados",
            "Sentidos Aguçados",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Lupus,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Eleva os sentidos do Garou a patamares lupinos (nas formas Hominídea/Glabro) ou a uma potência sobrenatural premonitória (nas formas Crinos, Hispo/...",
            "Eleva os sentidos do Garou a patamares lupinos (nas formas Hominídea/Glabro) ou a uma potência sobrenatural premonitória (nas formas Crinos, Hispo/...",
            "Line 1835"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RagabashEmbacamentoDaPropriaForma,
            "Embaçamento da Própria Forma",
            "Embaçamento da Própria Forma",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ragabash,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Stealth",
            8,
            WerewolfGiftDurationType.Scene,
            0,
            "Transforma o corpo do Garou em um borrão indistinto para passar despercebido. Teste de Manipulação + Furtividade (dificuldade 8). Cada sucesso aume...",
            "Transforma o corpo do Garou em um borrão indistinto para passar despercebido. Teste de Manipulação + Furtividade (dificuldade 8). Cada sucesso aume...",
            "Line 1877"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RagabashSimularOCheiroDeAguaCorrente,
            "Simular o Cheiro de Água Corrente",
            "Simular o Cheiro de Água Corrente",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ragabash,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Disfarça completamente o cheiro do Garou, tornando-o impossível de rastrear por faro. Habilidade inerente (aumenta em 2 pontos a dificuldade de qua...",
            "Disfarça completamente o cheiro do Garou, tornando-o impossível de rastrear por faro. Habilidade inerente (aumenta em 2 pontos a dificuldade de qua...",
            "Line 1880"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RagabashInduzirEsquecimento,
            "Induzir Esquecimento",
            "Induzir Esquecimento",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ragabash,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Wits",
            "Stealth",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Rouba um objeto de um alvo fazendo-o esquecer completamente que um dia o possuiu. Exige 3 sucessos em teste de Raciocínio + Furtividade contra a pa...",
            "Rouba um objeto de um alvo fazendo-o esquecer completamente que um dia o possuiu. Exige 3 sucessos em teste de Raciocínio + Furtividade contra a pa...",
            "Line 1887"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.TheurgeSentirAWyrm,
            "Sentir a Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Theurge,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Sentido místico para detectar manifestações da Wyrm (idêntico ao dos impuros). Teste de Percepção + Ocultismo (dificuldade variável conforme a inte...",
            "Sentido místico para detectar manifestações da Wyrm (idêntico ao dos impuros). Teste de Percepção + Ocultismo (dificuldade variável conforme a inte...",
            "Line 1928"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.PhilodoxFaroParaAFormaVerdadeira,
            "Faro Para a Forma Verdadeira",
            "Faro Para a Forma Verdadeira",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Philodox,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "PrimalInstinct",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Identifica a verdadeira natureza de um alvo através de uma sensação olfativa correspondente à sua forma natural. Identificação automática de lobiso...",
            "Identifica a verdadeira natureza de um alvo através de uma sensação olfativa correspondente à sua forma natural. Identificação automática de lobiso...",
            "Line 1970"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.PhilodoxVerdadeDeGaia,
            "Verdade de Gaia",
            "Verdade de Gaia",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Philodox,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Intelligence",
            "Empathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Percebe se um alvo está mentindo ou dizendo a verdade. Teste de Inteligência + Empatia contra a parada de Manipulação + Lábia do alvo. ### Dons de ...",
            "Percebe se um alvo está mentindo ou dizendo a verdade. Teste de Inteligência + Empatia contra a parada de Manipulação + Lábia do alvo. ### Dons de ...",
            "Line 1976"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.PhilodoxReiDosAnimais,
            "Rei dos Animais",
            "Rei dos Animais",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Philodox,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "AnimalEmpathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Exige a lealdade e obediência incondicional de um animal (um por vez). Teste de Carisma + Empatia com Animais contra dificuldade baseada na relação...",
            "Exige a lealdade e obediência incondicional de um animal (um por vez). Teste de Carisma + Empatia com Animais contra dificuldade baseada na relação...",
            "Line 1986"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GalliardComunicacaoComAnimais,
            "Comunicação com Animais",
            "Comunicação com Animais",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Galliard,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "AnimalEmpathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Comunica-se com qualquer espécie animal (sem alterar o temor natural que eles sentem de predadores). Teste de Carisma + Empatia com Animais (um tes...",
            "Comunica-se com qualquer espécie animal (sem alterar o temor natural que eles sentem de predadores). Teste de Carisma + Empatia com Animais (um tes...",
            "Line 2022"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GalliardDistracoes,
            "Distrações",
            "Distrações",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Galliard,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Emite ruídos irritantes para desviar a atenção e atrapalhar o oponente. Teste de Raciocínio + Performance contra a Força de Vontade do alvo. Cada s...",
            "Emite ruídos irritantes para desviar a atenção e atrapalhar o oponente. Teste de Raciocínio + Performance contra a Força de Vontade do alvo. Cada s...",
            "Line 2035"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounGarrasAfiadas,
            "Garras Afiadas",
            "Garras Afiadas",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Rage,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Afia as garras como navalhas ao raspá-las contra uma superfície dura. Custa 1 ponto de Fúria e exige um turno de preparação. Concede +1 dado de dan...",
            "Afia as garras como navalhas ao raspá-las contra uma superfície dura. Custa 1 ponto de Fúria e exige um turno de preparação. Concede +1 dado de dan...",
            "Line 2064"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounInspiracao,
            "Inspiração",
            "Inspiração",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Renova o ânimo, a coragem e a sede de justiça dos companheiros em combate. Custa 1 ponto de Gnose. Todos os aliados (exceto o usuário) ganham 1 suc...",
            "Renova o ânimo, a coragem e a sede de justiça dos companheiros em combate. Custa 1 ponto de Gnose. Todos os aliados (exceto o usuário) ganham 1 suc...",
            "Line 2067"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounEspiritoDaBatalha,
            "Espírito da Batalha",
            "Espírito da Batalha",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Permite atacar com velocidade fulminante, agindo antes de qualquer adversário. Habilidade inerente/permanente após aprendida. Concede +10 nos teste...",
            "Permite atacar com velocidade fulminante, agindo antes de qualquer adversário. Habilidade inerente/permanente após aprendida. Concede +10 nos teste...",
            "Line 2074"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounMedoVerdadeiro,
            "Medo Verdadeiro",
            "Medo Verdadeiro",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Strength",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Exibe o poder intimidador do Ahroun, forçando o adversário à quiescência. Teste de Força + Intimidação contra a Força de Vontade do alvo. Cada suce...",
            "Exibe o poder intimidador do Ahroun, forçando o adversário à quiescência. Teste de Força + Intimidação contra a Força de Vontade do alvo. Cada suce...",
            "Line 2077"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounSentirAPrata,
            "Sentir a Prata",
            "Sentir a Prata",
            2,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "PrimalInstinct",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Detecta a presença de armas ou objetos de prata nas proximidades. Teste de Percepção + Instinto Primitivo (dificuldade 7). Sucesso detecta a presen...",
            "Detecta a presença de armas ou objetos de prata nas proximidades. Teste de Percepção + Instinto Primitivo (dificuldade 7). Sucesso detecta a presen...",
            "Line 2080"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersSentidosCiberneticos,
            "Sentidos Cibernéticos",
            "Sentidos Cibernéticos",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Perception",
            "Science",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Substitui sentidos naturais por aparatos tecnológicos (radar, infravermelho, ultravioleta). Custa 1 ponto de Gnose por sentido e exige teste de Per...",
            "Substitui sentidos naturais por aparatos tecnológicos (radar, infravermelho, ultravioleta). Custa 1 ponto de Gnose por sentido e exige teste de Per...",
            "Line 2117"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersSobrecargaDeEnergia,
            "Sobrecarga de Energia",
            "Sobrecarga de Energia",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Comunica-se com a eletricidade para provocar um blecaute na região. Custa 1 ponto de Gnose e exige teste de Raciocínio + Ciência (dificuldade 7). A...",
            "Comunica-se com a eletricidade para provocar um blecaute na região. Custa 1 ponto de Gnose e exige teste de Raciocínio + Ciência (dificuldade 7). A...",
            "Line 2120"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisDeterAFugaDosCovardes,
            "Deter a Fuga dos Covardes",
            "Deter a Fuga dos Covardes",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Strength",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Reduz drasticamente a velocidade de movimento de um oponente em retirada. Exige 1 turno de concentração e teste de Carisma + Intimidação contra a F...",
            "Reduz drasticamente a velocidade de movimento de um oponente em retirada. Exige 1 turno de concentração e teste de Carisma + Intimidação contra a F...",
            "Line 2157"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisRugidoDoPredador,
            "Rugido do Predador",
            "Rugido do Predador",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Strength",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Emite um rosnado bestial que drena a confiança e a combatividade do oponente. Exige 1 turno para invocar e teste de Carisma + Intimidação contra Ra...",
            "Emite um rosnado bestial que drena a confiança e a combatividade do oponente. Exige 1 turno para invocar e teste de Carisma + Intimidação contra Ra...",
            "Line 2160"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaUivoDaBanshee,
            "Uivo da Banshee",
            "Uivo da Banshee",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Expression",
            8,
            WerewolfGiftDurationType.Turn,
            0,
            "Emite um uivo lamuriento e aterrorizante que induz pânico nos ouvintes. Gasta 1 ponto de Gnose e exige teste de Carisma + Intimidação. Os alvos dev...",
            "Emite um uivo lamuriento e aterrorizante que induz pânico nos ouvintes. Gasta 1 ponto de Gnose e exige teste de Carisma + Intimidação. Os alvos dev...",
            "Line 2200"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaResistenciaADor,
            "Resistência à Dor",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao dos Philodox.",
            "Idêntico ao dos Philodox.",
            "Line 2229"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaAcalmar,
            "Acalmar",
            "Acalmar",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Empathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Aplaca a raiva e drena pontos de Fúria de outras criaturas. Gasta 1 ponto de Gnose e exige teste de Carisma + Empatia (dificuldade igual à Força de...",
            "Aplaca a raiva e drena pontos de Fúria de outras criaturas. Gasta 1 ponto de Gnose e exige teste de Carisma + Empatia (dificuldade igual à Força de...",
            "Line 2234"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaArmaduraDeLuna,
            "Armadura de Luna",
            "Armadura de Luna",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            7,
            WerewolfGiftDurationType.Turn,
            0,
            "Invoca a proteção de Luna, garantindo resiliência defensiva inclusive contra a prata. Concentração de 1 turno, gasto de 1 Gnose e teste de Vigor + ...",
            "Invoca a proteção de Luna, garantindo resiliência defensiva inclusive contra a prata. Concentração de 1 turno, gasto de 1 Gnose e teste de Vigor + ...",
            "Line 2237"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesMaldicaoDeEolo,
            "Maldição de Éolo",
            "Maldição de Éolo",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Expression",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Convoca uma neblina espessa e lúgubre que desorienta os inimigos, enquanto permite visão clara à Fúria. Teste de Gnose (dificuldade baseada no terr...",
            "Convoca uma neblina espessa e lúgubre que desorienta os inimigos, enquanto permite visão clara à Fúria. Teste de Gnose (dificuldade baseada no terr...",
            "Line 2271"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesSentirAPresa,
            "Sentir a Presa",
            "Sentir a Presa",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao dos Ragabash. ### Dons de Nível 3",
            "Idêntico ao dos Ragabash. ### Dons de Nível 3",
            "Line 2274"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsMenteAnimal,
            "Mente Animal",
            "Mente Animal",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Suprime temporariamente as faculdades mentais superiores de uma vítima, reduzindo-a aos instintos de um animal. Teste de Manipulação + Empatia (dif...",
            "Suprime temporariamente as faculdades mentais superiores de uma vítima, reduzindo-a aos instintos de um animal. Teste de Manipulação + Empatia (dif...",
            "Line 2307"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsSentirAPresa,
            "Sentir a Presa",
            "Sentir a Presa",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao dos Ragabash. ### Dons de Nível 3",
            "Idêntico ao dos Ragabash. ### Dons de Nível 3",
            "Line 2310"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersSentirAWyrm,
            "Sentir a Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos impuros.",
            "Idêntico ao Dom dos impuros.",
            "Line 2337"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersGerarIgnorancia,
            "Gerar Ignorância",
            "Gerar Ignorância",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos Ragabash.",
            "Idêntico ao Dom dos Ragabash.",
            "Line 2346"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersResistenciaDeMensageiro,
            "Resistência de Mensageiro",
            "Resistência de Mensageiro",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Permite correr à velocidade máxima por três dias consecutivos sem necessidade de descanso, comida ou água. Gasta 1 ponto de Gnose. O Garou não pode...",
            "Permite correr à velocidade máxima por três dias consecutivos sem necessidade de descanso, comida ou água. Gasta 1 ponto de Gnose. O Garou não pode...",
            "Line 2348"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsSentirAWyrm,
            "Sentir a Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos impuros. ### Dons de Nível 2",
            "Idêntico ao Dom dos impuros. ### Dons de Nível 2",
            "Line 2380"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsArmaduraDeLuna,
            "Armadura de Luna",
            "Armadura de Luna",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos Filhos de Gaia.",
            "Idêntico ao Dom dos Filhos de Gaia.",
            "Line 2383"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsEmpatia,
            "Empatia",
            "Empatia",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Concede percepção aguçada sobre o que o público ou grupo espera e deseja ver de seu líder. Gasta 1 ponto de Gnose e exige teste de Inteligência + E...",
            "Concede percepção aguçada sobre o que o público ou grupo espera e deseja ver de seu líder. Gasta 1 ponto de Gnose e exige teste de Inteligência + E...",
            "Line 2385"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersGerarIgnorancia,
            "Gerar Ignorância",
            "Gerar Ignorância",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos Ragabash.",
            "Idêntico ao Dom dos Ragabash.",
            "Line 2420"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersOdorRepugnante,
            "Odor Repugnante",
            "Odor Repugnante",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Amplifica o odor corporal para debilitar e afastar oponentes nas proximidades. Gasta 1 ponto de Gnose. Subtrai 2 dados de todas as paradas de seres...",
            "Amplifica o odor corporal para debilitar e afastar oponentes nas proximidades. Gasta 1 ponto de Gnose. Subtrai 2 dados de todas as paradas de seres...",
            "Line 2422"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsAplausoTrovejante,
            "Aplauso Trovejante",
            "Aplauso Trovejante",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            "Strength",
            "Brawl",
            8,
            WerewolfGiftDurationType.Turn,
            0,
            "Gera uma trovoada ensurdecedora batendo palmas, atordoando alvos próximos. Gasta 1 ponto de Gnose. Alvos num raio de 3 metros testam Força de Vonta...",
            "Gera uma trovoada ensurdecedora batendo palmas, atordoando alvos próximos. Gasta 1 ponto de Gnose. Alvos num raio de 3 metros testam Força de Vonta...",
            "Line 2458"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsArmaduraDeLuna,
            "Armadura de Luna",
            "Armadura de Luna",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos Filhos de Gaia. ### Dons de Nível 3",
            "Idêntico ao Dom dos Filhos de Gaia. ### Dons de Nível 3",
            "Line 2461"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaEspiritoDoPassaro,
            "Espírito do Pássaro",
            "Espírito do Pássaro",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Permite ao Garou adejar, flutuar ou voar livremente pelos céus. Gasta 1 ponto de Gnose. Permite voar a 32 km/h por uma hora. Aumenta em 1 ponto a d...",
            "Permite ao Garou adejar, flutuar ou voar livremente pelos céus. Gasta 1 ponto de Gnose. Permite voar a 32 km/h por uma hora. Aumenta em 1 ponto a d...",
            "Line 2498"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaEspiritoDoPeixe,
            "Espírito do Peixe",
            "Espírito do Peixe",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "AnimalEmpathy",
            7,
            WerewolfGiftDurationType.Turn,
            0,
            "Concede a capacidade de respirar debaixo d'água e nadar com a mesma velocidade da forma Hispo. Gasta 1 ponto de Gnose e exige teste de Vigor + Empa...",
            "Concede a capacidade de respirar debaixo d'água e nadar com a mesma velocidade da forma Hispo. Gasta 1 ponto de Gnose e exige teste de Vigor + Empa...",
            "Line 2501"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoResistenciaADor,
            "Resistência à Dor",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Idêntico ao Dom dos Philodox. ### Dons de Nível 2",
            "Idêntico ao Dom dos Philodox. ### Dons de Nível 2",
            "Line 2533"),        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoVentoCortante,
            "Vento Cortante",
            "Vento Cortante",
            2,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Occult",
            null,
            WerewolfGiftDurationType.Turn,
            0,
            "Dispara uma rajada de vento extremamente fria e cortante capaz de derrubar oponentes e congelá-los. Gasta 1 ponto de Força de Vontade e exige teste...",
            "Dispara uma rajada de vento extremamente fria e cortante capaz de derrubar oponentes e congelá-los. Gasta 1 ponto de Força de Vontade e exige teste...",
            "Line 2539"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidPersuasao,
            "Persuasion",
            "Persuasão",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Makes the Homid more persuasive and credible. On success, the Narrator reduces all Social test difficulties by 1 for the rest of the scene.",
            "Torna o hominídeo mais persuasivo e credível. Em caso de sucesso, o Narrador reduz em 1 ponto as dificuldades de todos os testes Sociais durante o resto da cena.",
            "Line 1736"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidFitar,
            "Fascinate",
            "Fitar",
            2,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Fixes gaze on target to cause flight or immobility. Test Charisma + Intimidation vs target Willpower + Athletics. Each success forces target to flee or prevents attacks.",
            "Fixa o olhar em um humano ou animal para fazê-lo fugir aterrorizado ou imobilizar alvos sobrenaturais. Cada sucesso derruba/imobiliza a vítima.",
            "Line 1743"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidInquietacao,
            "Unrest",
            "Inquietação",
            3,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Empathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Causes inexplicable depression and apathy. Test Manipulation + Empathy vs target Willpower. Target cannot recover Rage this scene and prolonged action difficulties increase by 1.",
            "Causa depressão inexplicável e apatia no alvo. Teste de Manipulação + Empatia contra a Força de Vontade do alvo. Oponente não recupera Fúria durante a cena.",
            "Line 1758"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidRemodelarObjeto,
            "Reshape Object",
            "Remodelar Objeto",
            3,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Manipulation",
            "Crafts",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Shapes living material into tools, weapons, or shelter. Test Manipulation + Crafts. Variable duration by successes. Extra Gnosis creates aggravated weapons or permanent alteration.",
            "Modela material vivo transformando-o em ferramentas, armas ou abrigos. Teste de Manipulação + Ofícios. Duração variável por sucessos. Gnose extra cria dano agravado ou alteração permanente.",
            "Line 1761"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidCasulo,
            "Cocoon",
            "Casulo",
            4,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Ignores attacks that do not cause damage equal or superior to Vigor + Rituals. Piercing attacks destroy the cocoon. Lasts a scene.",
            "Ignora ataques que não causem dano igual ou superior à sua parada de Vigor + Rituais. Ataques que perfurem o casulo o destroem. Dura uma cena.",
            "Line 1772"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaRemodelarObjeto,
            "Reshape Object",
            "Remodelar Objeto",
            3,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Crafts",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Shapes living material into tools, weapons, or shelter. Same mechanics as Homid Remodelar Objeto. Variable duration by successes.",
            "Modela material vivo transformando-o em ferramentas, armas ou abrigos. Mesma mecânica que o Dom dos Hominídeos. Duração variável por sucessos.",
            "Line 2207"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersRemodelarObjeto,
            "Reshape Object",
            "Remodelar Objeto",
            3,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Manipulation",
            "Crafts",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Shapes living material into tools, weapons, or shelter. Same mechanics as Homid Remodelar Objeto. Variable duration by successes.",
            "Modela material vivo transformando-o em ferramentas, armas ou abrigos. Mesma mecânica que o Dom dos Hominídeos. Duração variável por sucessos.",
            "Line 2429"),
    };

    public static IReadOnlyDictionary<string, WerewolfGiftDefinition> ByKey { get; } =
        new ReadOnlyDictionary<string, WerewolfGiftDefinition>(All.ToDictionary(g => g.GiftKey, StringComparer.Ordinal));

    public static IReadOnlyList<WerewolfGiftDefinition> AllDefinitions { get; } = Array.AsReadOnly(All);

    public static WerewolfGiftDefinition? Get(string giftKey)
    {
        if (string.IsNullOrWhiteSpace(giftKey))
        {
            return null;
        }

        return ByKey.TryGetValue(giftKey, out var definition) ? definition : null;
    }

    public static bool IsKnown(string? giftKey)
    {
        return !string.IsNullOrWhiteSpace(giftKey) && ByKey.ContainsKey(giftKey);
    }
}