using System.Collections.ObjectModel;

namespace Chronicle.RuleSets.Werewolf.CharacterCreation;

public static class WerewolfGiftCatalog
{
    private static readonly WerewolfGiftDefinition[] All = new[]
    {
        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.HomidMasterOfFire,
            "Master of Fire",
            "Mestre do Fogo",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Homid,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Repairs fire damage as bashing for the scene.",
            "Repara dano por fogo como contusão durante a cena.",
            "Line 1733"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.MetisCreateElement,
            "Create Element",
            "Criar Elemento",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Metis,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Gnosis",
            null,
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Creates a small amount of natural element (earth, water, fire, air). Each success creates about 30 cubic centimeters (up to 50 kg) within 20 meters. Created flames cause 1 health level per success (max 3).",
            "Cria pequena quantidade de elemento natural (terra, água, fogo, ar). Cada sucesso cria cerca de 30 cm³ (até 50 kg) num raio de 20 metros. Chamas causam 1 nível de dano por sucesso (máx 3).",
            "Line 1788"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.LupusHareLeap,
            "Hare Leap",
            "Salto da Lebre",
            1,
            WerewolfGiftCategory.Breed,
            WerewolfRaceIdentifiers.Lupus,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Athletics",
            7,
            WerewolfGiftDurationType.Instant,
            0,
            "Doubles the Garou's normal jump distance on a successful test.",
            "Dobra a distância normal de salto do Garou em caso de sucesso.",
            "Line 1827"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RagabashOpenSeal,
            "Open Seal",
            "Abrir Objetos",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ragabash,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Opens almost any physical locked device. Difficulty equals local Película level.",
            "Abre quase qualquer dispositivo físico trancado. Dificuldade igual ao nível local da Película.",
            "Line 1874"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.TheurgeSpiritSpeech,
            "Spirit Speech",
            "Comunicação com Espíritos",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Theurge,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Intuitively understands the language of spirits encountered casually, even if they do not wish to dialogue.",
            "Compreende intuitivamente a linguagem de espíritos encontrados casualmente, mesmo que não desejem dialogar.",
            "Line 1925"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.PhilodoxResistPain,
            "Resist Pain",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Philodox,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Ignores all wound penalties for the rest of the scene through force of will.",
            "Ignora completamente todas as penalidades de ferimentos durante o resto da cena.",
            "Line 1973"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GalliardBeastSpeech,
            "Beast Speech",
            "Chamado da Wyrm / Chamado da Wyld",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Galliard,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Empathy",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Emits a vigorous howl that mobilizes packs at great distances and exhorts the sept. The Narrator defines applicable bonuses.",
            "Emite um uivo vigoroso que mobiliza matilhas a grandes distâncias e exorta a seita. O Narrador define os bônus aplicáveis.",
            "Line 2019"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.AhrounFallingTouch,
            "Falling Touch",
            "Toque da Queda",
            1,
            WerewolfGiftCategory.Auspice,
            WerewolfAuspiceIdentifiers.Ahroun,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Medicine",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Knocks the opponent prone with a simple touch. Test Dexterity + Medicine vs target Vigor + Athletics. Each success knocks the victim down.",
            "Derruba o adversário ao solo com um simples toque. Teste de Destreza + Medicina contra Vigor + Esportes do alvo. Cada sucesso derruba a vítima.",
            "Line 2070"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersControlSimpleMachine,
            "Control Simple Machine",
            "Controle de Máquinas Simples",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Willpower,
            1,
            "Manipulation",
            "Crafts",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Commands spirits of simple machines (levers, doors, pulleys).",
            "Comanda espíritos de máquinas simples (alavancas, portas, roldanas).",
            "Line 2107"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersDiagnostics,
            "Diagnostics",
            "Diagnosticar",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Perception",
            "Crafts",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Instantly identifies mechanical defects and convinces the machine spirit to assist in repair. Reduces repair time by half and subtracts successes from total repair difficulty.",
            "Identifica defeitos mecânicos instantaneamente e convence o espírito da máquina a auxiliar no conserto. Reduz o tempo de reparo pela metade.",
            "Line 2110"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GlassWalkersTrickShot,
            "Trick Shot",
            "Número de Tiro",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GlassWalkers,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Adds permanent Glory rating to indirect shooting maneuvers. Does not cause direct damage.",
            "Adiciona o nível de Glória permanente à parada de dados em manobras de tiro indiretas. Não causa dano direto.",
            "Line 2113"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisRazorClaws,
            "Razor Claws",
            "Garras Afiadas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Rage,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Sharpens claws like razors against a hard surface. Grants +1 damage die with claw attacks for the scene. Requires 1 turn of preparation.",
            "Afi as garras como navalhas ao raspá-las contra uma superfície dura. Concede +1 dado de dano em ataques com garras durante a cena. Requer 1 turno de preparação.",
            "Line 2147"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisResistPain,
            "Resist Pain",
            "Resistência à Dor",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Ignores all wound penalties for the rest of the scene through force of will.",
            "Ignora completamente todas as penalidades de ferimentos durante o resto da cena.",
            "Line 2150"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.GetOfFenrisVisageOfFenris,
            "Visage of Fenris",
            "Semblante de Fenris",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.GetOfFenris,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Intimidation",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Assumes a larger, fearsome physical presence that inspires allies and terrifies rivals. Grants +1 to Social tests for allies and -1 to initiative for adversaries. Duration: one scene.",
            "Assume um porte físico maior, temível e imponente que inspira aliados e aterroriza rivais. Concede +1 em testes Sociais para aliados e -1 na iniciativa de adversários. Dura uma cena.",
            "Line 2153"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaFaerieLight,
            "Faerie Light",
            "Luz das Fadas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Wits",
            "Enigmas",
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Conjures a small bouncing sphere of light to illuminate the environment or distract enemies. Lasts 1 turn per success, or the entire scene with 1 Gnosis point.",
            "Conjura uma pequena esfera de luz saltitante para iluminar o ambiente ou distrair inimigos. Dura 1 turno por sucesso, ou a cena toda com 1 ponto de Gnose.",
            "Line 2188"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaPersuasion,
            "Persuasion",
            "Persuasão",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Makes the Fianna more persuasive and credible when interacting with others. On success, the Narrator reduces all Social test difficulties by 1 for the rest of the scene.",
            "Torna o Fianna mais persuasivo e credível ao interagir com outras pessoas. Em caso de sucesso, o Narrador reduz em 1 ponto as dificuldades de todos os testes Sociais durante o resto da cena.",
            "Line 2191"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.FiannaResistToxin,
            "Resist Toxin",
            "Resistência a Toxinas",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Fianna,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Stamina",
            "Survival",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Adapts the organism to nullify common poisons after festive rituals. Cancels common poisons and grants +3 dice to Stamina against Wyrm toxins for the scene.",
            "Adapta o organismo para anular venenos convencionais após rituais festivos. Anula venenos comuns e concede +3 dados ao Vigor contra toxinas da Wyrm durante uma cena.",
            "Line 2193"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaMercy,
            "Mercy",
            "Misericórdia",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "All natural body damage (claws and fangs, without weapons) becomes bashing for the scene.",
            "Todo o dano infligido pelo próprio corpo (garras e dentes, sem armas) torna-se contundente durante a cena.",
            "Line 2226"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ChildrenOfGaiaMothersTouch,
            "Mother's Touch",
            "Toque da Mãe",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ChildrenOfGaia,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.Gnosis,
            1,
            "Intelligence",
            "Medicine",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Heals wounds (including aggravated) of any living creature by touch. Each success repairs 1 health level. Difficulty equals target's Fury or 6 for non-Garou. Can heal Battle Scars with a second Gnosis point in the same scene.",
            "Cicatriza ferimentos (inclusive agravados) de qualquer criatura viva por imposição de mãos. Cada sucesso repara 1 nível de vitalidade. Dificuldade igual à Fúria do alvo ou 6 para não-Garou.",
            "Line 2231"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesBreathOfTheWyrm,
            "Breath of the Wyrm",
            "Hálito da Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            6,
            WerewolfGiftDurationType.Scene,
            0,
            "Requires touch to open sky in natural environment. Grants +1 die to Mental tests and +1 difficulty to target's Fury tests for the next scene. Difficulty 6 for humans, 5 for Garou.",
            "Requer toque a céu aberto em ambiente natural. Concede +1 dado em testes Mentais e +1 na dificuldade de testes de Fúria do alvo na cena seguinte.",
            "Line 2263"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesHeightenedSenses,
            "Heightened Senses",
            "Sentidos Aguçados",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Elevates senses to lupine levels. Homid/Glabro: reduces Perception difficulties by 2. Crinos/Hispo/Lupus: reduces Perception difficulties by 3 and grants +1 die to Primal Instinct.",
            "Eleva os sentidos a patamares lupinos. Hominídea/Glabro: reduz em 2 as dificuldades de Percepção. Crinos/Hispo/Lupina: reduz em 3 as dificuldades de Percepção e concede +1 dado em Instinto Primitivo.",
            "Line 2266"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BlackFuriesSenseWyrm,
            "Sense Wyrm",
            "Sentir a Wyrm",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BlackFuries,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Mystic sense to detect Wyrm manifestations, objects, or people tainted by the Wyrm. Difficulty 6 for a nearby fomor, 8 for a Cursed one's trail.",
            "Sentido místico para perceber manifestações, objetos ou pessoas maculadas pela Wyrm. Dificuldade 6 para um fomor próximo, 8 para o rastro de um Maldito.",
            "Line 2268"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsBeastSpeech,
            "Beast Speech",
            "Comunicação com Animais",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "AnimalEmpathy",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Communicates with any animal species. One test per species/encounter.",
            "Comunica-se com qualquer espécie animal. Um teste por espécie/encontro.",
            "Line 2299"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsWolfAtTheDoor,
            "Wolf at the Door",
            "O Lobo Bate à Porta",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "PrimalInstinct",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Infuses humans with primal fear and deep aversion to the forest. Direct eye contact required. Target hesitates to leave home and loses 2 dice on all Mental and Social tests for the scene.",
            "Infunde em seres humanos um medo primal e aversão profunda à floresta. Contato visual direto. O alvo hesita em sair de casa e perde 2 dados em paradas Mentais e Sociais durante a cena.",
            "Line 2301"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.RedTalonsScentOfRunningWater,
            "Scent of Running Water",
            "Simular o Cheiro de Água Corrente",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.RedTalons,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Completely disguises the Garou's scent, making it impossible to track by smell. Increases difficulty of any tracking test by 2.",
            "Disfarça completamente o cheiro do Garou, tornando-o impossível de rastrear por faro. Aumenta em 2 pontos a dificuldade de qualquer teste para rastrear o personagem.",
            "Line 2304"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersSilence,
            "Silence",
            "Silêncio",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Muffles any sound produced by the Garou to facilitate stealthy approaches. Each success adds +1 to the difficulty of others hearing the Garou during the scene.",
            "Abafa qualquer som produzido pelo Garou para facilitar aproximações furtivas. Cada sucesso adiciona +1 ponto à dificuldade de outras pessoas ouvirem o Garou durante uma cena.",
            "Line 2339"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilentStridersSpeedOfThought,
            "Speed of Thought",
            "Velocidade do Pensamento",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilentStriders,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Instantly doubles the Garou's running speed for the scene.",
            "Duplica instantaneamente a velocidade de corrida do lobisomem durante a cena.",
            "Line 2342"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsLambentFlame,
            "Lambent Flame",
            "Chama Tremulante",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Willpower,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Envelopes the body in bright silver light that protects against direct attacks and illuminates the environment (15-meter radius). Unarmed attacks against the Garou receive +1 difficulty, while ranged attacks receive -1 bonus.",
            "Envolve o corpo em uma luz prateada brilhante que protege contra ataques diretos e ilumina o ambiente (raio de 15 metros). Ataques desarmados recebem +1 de dificuldade, enquanto ataques à distância recebem -1 de bônus.",
            "Line 2374"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.SilverFangsFalconsGrasp,
            "Falcon's Grasp",
            "Nas Garras do Falcão",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.SilverFangs,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Rage,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Allows closing hands or jaws hermetically, making it nearly impossible to escape the grip. Strength is considered +3 for grapples and jaw maneuvers without adding damage. Can activate both hands/jaws for 2 Rage.",
            "Permite fechar as mãos ou mandíbulas de forma hermética, tornando quase impossível escapar do aperto. A Força é considerada 3 pontos superior em agarramentos e manobras de mandíbula de ferro.",
            "Line 2377"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersCooking,
            "Cooking",
            "Culinária",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Wits",
            "Survival",
            6,
            WerewolfGiftDurationType.Instant,
            0,
            "Converts trash, scrap metal, or debris into an edible, satisfying mash. Difficulty 6 for harmless materials, 10 for toxic substances.",
            "Converte lixo, jatos de metal ou detritos em um mingau comestível e saciador. Dificuldade 6 para materiais inócuos, 10 para substâncias tóxicas.",
            "Line 2411"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.BoneGnawersStickyFingers,
            "Sticky Fingers",
            "Grude",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.BoneGnawers,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            null,
            WerewolfGiftDurationType.Scene,
            1,
            "Allows joking with a pack or caern totem to obtain temporary treatment as a member. Requires prostration. Grants benefits for one day.",
            "Permite gracejar-se com o totem de uma matilha ou de um caern para obter tratamento temporário como membro. Requer prostração. Concede os benefícios por um dia.",
            "Line 2414"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsSeizingTheEdge,
            "Seizing the Edge",
            "Aproveitar a Vantagem",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.Active,
            WerewolfGiftCostType.Gnosis,
            1,
            null,
            null,
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Inclines resisted tests and ties in favor of the Shadow Lord. Lasts one entire scene.",
            "Inclina testes resistidos e empates a favor do Senhor das Sombras. Dura uma cena inteira.",
            "Line 2448"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsAuraOfConfidence,
            "Aura of Confidence",
            "Aura de Confiança",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Charisma",
            "Subterfuge",
            7,
            WerewolfGiftDurationType.Scene,
            0,
            "Projects a superior and controlled aura that blocks aura analysis and flaw detection. Active for one scene on success.",
            "Projeta uma aura superior e controlada que bloqueia análises de aura e detecção de falhas. Ativa por uma cena em caso de sucesso.",
            "Line 2451"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.ShadowLordsFatalFlaw,
            "Fatal Flaw",
            "Fraquezas Fatais",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.ShadowLords,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Empathy",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Identifies critical vulnerabilities of a target to maximize damage in combat. Requires 1 turn of concentration. Each success grants +1 damage die for the scene. Difficulty equals target's Wits + Subterfuge.",
            "Identifica vulnerabilidades críticas de um alvo para maximizar o dano em combate. Requer 1 turno de concentração. Cada sucesso concede +1 dado de dano para a cena.",
            "Line 2454"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaSpiritSpeech,
            "Spirit Speech",
            "Comunicação com Espíritos",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Intuitively understands the language of spirits encountered casually, even if they do not wish to dialogue. Identical to Theurge Spirit Speech.",
            "Compreende intuitivamente a linguagem de espíritos encontrados casualmente, mesmo que não desejem dialogar. Idêntico ao Dom dos Theurges.",
            "Line 1925"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaShroud,
            "Shroud",
            "Mortalha",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.Passive,
            WerewolfGiftCostType.None,
            0,
            null,
            null,
            null,
            WerewolfGiftDurationType.Permanent,
            0,
            "Conceals the Uktena from supernatural detection. Spirits and magical senses find it harder to perceive the Uktena.",
            "Concele o Uktena de detecção sobrenatural. Espíritos e sentidos mágicos têm mais dificuldade em perceber o Uktena.",
            "Line 831"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.UktenaSenseMagic,
            "Sense Magic",
            "Sentir Magia",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Uktena,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Perception",
            "Occult",
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Detects magical auras, fetishes, and active enchantments in the vicinity.",
            "Detecta auras mágicas, fetiches e encantamentos ativos nas proximidades.",
            "Line 831"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoCamouflage,
            "Camouflage",
            "Camuflagem",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Dexterity",
            "Stealth",
            null,
            WerewolfGiftDurationType.Scene,
            0,
            "Blends into snowy or natural terrain. Each success adds +1 difficulty to Perception tests to spot the Wendigo. In snow, this can be nearly automatic.",
            "Mistura-se com terreno nevado ou natural. Cada sucesso adiciona +1 de dificuldade a testes de Percepção para detectar o Wendigo.",
            "Line 848"),

        new WerewolfGiftDefinition(
            WerewolfGiftIdentifiers.WendigoCallTheBreeze,
            "Call the Breeze",
            "Invocar a Brisa",
            1,
            WerewolfGiftCategory.Tribe,
            WerewolfTribeIdentifiers.Wendigo,
            WerewolfGiftActivationType.TestRequired,
            WerewolfGiftCostType.None,
            0,
            "Gnosis",
            null,
            null,
            WerewolfGiftDurationType.Instant,
            0,
            "Summons a chill wind or breeze. Can be used to cool the environment, carry scents, or obscure vision slightly.",
            "Invoca um vento frio ou brisa. Pode ser usado para resfriar o ambiente, carregar odores ou obscurecer a visão levemente.",
            "Line 848")
    };

    public static IReadOnlyDictionary<string, WerewolfGiftDefinition> ByKey { get; } =
        new ReadOnlyDictionary<string, WerewolfGiftDefinition>(All.ToDictionary(g => g.GiftKey, StringComparer.Ordinal));

    public static IReadOnlyList<WerewolfGiftDefinition> AllDefinitions { get; } = Array.AsReadOnly(All);

    public static WerewolfGiftDefinition? Get(string giftKey)
    {
        if (string.IsNullOrWhiteSpace(giftKey))
        {
            return null;
        }

        return ByKey.TryGetValue(giftKey, out var definition) ? definition : null;
    }

    public static bool IsKnown(string? giftKey)
    {
        return !string.IsNullOrWhiteSpace(giftKey) && ByKey.ContainsKey(giftKey);
    }
}